### ISSUE TITLE
Browsers fail to load resources (ttf, woff)

### ISSUE THREAD

**Issue by fongreecss** [lykmapipo/themify-icons#1]
I've been using themify-icons on one of my WordPress projects online. Fonts worked well on localhost, but failed after I deployed them online. I've tested this only on latest Chrome and Firefox. I've found the problem is in these lines of codes:

``` css
@font-face {
    font-family: 'themify';
    src:url('fonts/themify.eot?-fvbane');
    src:url('fonts/themify.eot?#iefix-fvbane') format('embedded-opentype'),
        url('fonts/themify.woff?-fvbane') format('woff'),
        url('fonts/themify.ttf?-fvbane') format('truetype'),
        url('fonts/themify.svg?-fvbane#themify') format('svg');
    font-weight: normal;
    font-style: normal;
}
```

After removing fvbane from it it worked fine

``` css
@font-face {
    font-family: 'themify';
    src:url('fonts/themify.eot');
    src:url('fonts/themify.eot?#iefix') format('embedded-opentype'),
        url('fonts/themify.woff') format('woff'),
        url('fonts/themify.ttf') format('truetype'),
        url('fonts/themify.svg') format('svg');
    font-weight: normal;
    font-style: normal;
}
```
